# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df58394bd20c5d9c4e164d6de201a800ba2103c510bb82821c6219fc33f5bfd0a149e781cd7611e45730522d5db98884d83a07d04670a6ed49fe4e048dd21dcc

test:
  secret_key_base: 919de8b15c3bc177a4ef28bc08712e7e7acc016eb77f13400e35ad06256debecf2b128ec756151c686debb807a07b4fc269c88b6fa6a07912d04021e95529c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
